typography_spectrum: 0.6145547246560454
content_rating:
  adult: false
color:
  brandStrength: 0.3583290034439415
  lightness: 0.717321791453287
  saturation: 0.30017148121260107
  rhythmicContrast: 0.2786434006411582
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
layout_spectrum: 0.2281646670307964
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd18a56d-d749-4095-8d64-da9501692c4c.png
name: PhotoshopXXX
navigation:
  - id: >-
      http://www.pornhubpremium.com/premium_signup?join=13&ats=eyJhIjo4NTI5NCwiYyI6NDQyODkwNzgsIm4iOjMsInMiOjIsImUiOjQyMiwicCI6MTF9
    url: >-
      http://www.pornhubpremium.com/premium_signup?join=13&ats=eyJhIjo4NTI5NCwiYyI6NDQyODkwNzgsIm4iOjMsInMiOjIsImUiOjQyMiwicCI6MTF9
    name: PornHub Premium
    type: external
